//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BGL.CompareTheMarket.Services.DistributorService.DataContracts")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://BGL.CompareTheMarket.Services.DistributorService.DataContracts", IsNullable=false)]
public partial class QuoteResults {
    
    private QuoteResultType[] quoteResultField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("QuoteResult")]
    public QuoteResultType[] QuoteResult {
        get {
            return this.quoteResultField;
        }
        set {
            this.quoteResultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BGL.CompareTheMarket.Services.DistributorService.DataContracts")]
public partial class QuoteResultType {
    
    private QuoteResultTypeHeader headerField;
    
    private QuotesType quotesField;
    
    private QuoteResultTypeMessages messagesField;
    
    /// <remarks/>
    public QuoteResultTypeHeader Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    public QuotesType Quotes {
        get {
            return this.quotesField;
        }
        set {
            this.quotesField = value;
        }
    }
    
    /// <remarks/>
    public QuoteResultTypeMessages Messages {
        get {
            return this.messagesField;
        }
        set {
            this.messagesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BGL.CompareTheMarket.Services.DistributorService.DataContracts")]
public partial class QuoteResultTypeHeader {
    
    private ResultStatus resultStatusField;
    
    /// <remarks/>
    public ResultStatus ResultStatus {
        get {
            return this.resultStatusField;
        }
        set {
            this.resultStatusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BGL.CompareTheMarket.Services.DistributorService.DataContracts")]
public enum ResultStatus {
    
    /// <remarks/>
    COMPLETE,
    
    /// <remarks/>
    ERROR,
    
    /// <remarks/>
    FILTERED,
    
    /// <remarks/>
    TIMEOUT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BGL.CompareTheMarket.Services.DistributorService.DataContracts")]
public partial class MessageDetailsType {
    
    private string messageFieldField;
    
    private string messageTextField;
    
    /// <remarks/>
    public string MessageField {
        get {
            return this.messageFieldField;
        }
        set {
            this.messageFieldField = value;
        }
    }
    
    /// <remarks/>
    public string MessageText {
        get {
            return this.messageTextField;
        }
        set {
            this.messageTextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BGL.CompareTheMarket.Services.DistributorService.DataContracts")]
public partial class GenericProduct {
    
    private ProductCodeType codeField;
    
    private decimal productCostField;
    
    private FeatureType typeField;
    
    /// <remarks/>
    public ProductCodeType Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public decimal ProductCost {
        get {
            return this.productCostField;
        }
        set {
            this.productCostField = value;
        }
    }
    
    /// <remarks/>
    public FeatureType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BGL.CompareTheMarket.Services.DistributorService.DataContracts")]
public enum ProductCodeType {
    
    /// <remarks/>
    BDF,
    
    /// <remarks/>
    DTA,
    
    /// <remarks/>
    DTI,
    
    /// <remarks/>
    LST,
    
    /// <remarks/>
    ADL,
    
    /// <remarks/>
    TPL,
    
    /// <remarks/>
    TPX,
    
    /// <remarks/>
    QRC,
    
    /// <remarks/>
    LPP,
    
    /// <remarks/>
    VFA,
    
    /// <remarks/>
    VFC,
    
    /// <remarks/>
    VFE,
    
    /// <remarks/>
    CPX,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BGL.CompareTheMarket.Services.DistributorService.DataContracts")]
public enum FeatureType {
    
    /// <remarks/>
    unlimited,
    
    /// <remarks/>
    gbp,
    
    /// <remarks/>
    gbpAnnual,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("gbp")]
    gbp1,
    
    /// <remarks/>
    gbpPerYear,
    
    /// <remarks/>
    percent,
    
    /// <remarks/>
    orPercent,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BGL.CompareTheMarket.Services.DistributorService.DataContracts")]
public partial class PremiumType {
    
    private decimal annualPremiumField;
    
    private PremiumTypeInstalmentDetails instalmentDetailsField;
    
    /// <remarks/>
    public decimal AnnualPremium {
        get {
            return this.annualPremiumField;
        }
        set {
            this.annualPremiumField = value;
        }
    }
    
    /// <remarks/>
    public PremiumTypeInstalmentDetails InstalmentDetails {
        get {
            return this.instalmentDetailsField;
        }
        set {
            this.instalmentDetailsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BGL.CompareTheMarket.Services.DistributorService.DataContracts")]
public partial class PremiumTypeInstalmentDetails {
    
    private decimal depositField;
    
    private string numberOfPaymentsField;
    
    private decimal monthlyPremiumField;
    
    /// <remarks/>
    public decimal Deposit {
        get {
            return this.depositField;
        }
        set {
            this.depositField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string NumberOfPayments {
        get {
            return this.numberOfPaymentsField;
        }
        set {
            this.numberOfPaymentsField = value;
        }
    }
    
    /// <remarks/>
    public decimal MonthlyPremium {
        get {
            return this.monthlyPremiumField;
        }
        set {
            this.monthlyPremiumField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BGL.CompareTheMarket.Services.DistributorService.DataContracts")]
public partial class LinkDetailsType {
    
    private string referenceField;
    
    private string usernameField;
    
    private string passwordField;
    
    private string retrievalLinkField;
    
    /// <remarks/>
    public string Reference {
        get {
            return this.referenceField;
        }
        set {
            this.referenceField = value;
        }
    }
    
    /// <remarks/>
    public string Username {
        get {
            return this.usernameField;
        }
        set {
            this.usernameField = value;
        }
    }
    
    /// <remarks/>
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    public string RetrievalLink {
        get {
            return this.retrievalLinkField;
        }
        set {
            this.retrievalLinkField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BGL.CompareTheMarket.Services.DistributorService.DataContracts")]
public partial class QuoteResultGenericQuote {
    
    private string brandField;
    
    private string insurerNameField;
    
    private LinkDetailsType linkDetailsField;
    
    private PremiumType premiumField;
    
    private QuoteResultGenericQuoteOtherProducts otherProductsField;
    
    /// <remarks/>
    public string Brand {
        get {
            return this.brandField;
        }
        set {
            this.brandField = value;
        }
    }
    
    /// <remarks/>
    public string InsurerName {
        get {
            return this.insurerNameField;
        }
        set {
            this.insurerNameField = value;
        }
    }
    
    /// <remarks/>
    public LinkDetailsType LinkDetails {
        get {
            return this.linkDetailsField;
        }
        set {
            this.linkDetailsField = value;
        }
    }
    
    /// <remarks/>
    public PremiumType Premium {
        get {
            return this.premiumField;
        }
        set {
            this.premiumField = value;
        }
    }
    
    /// <remarks/>
    public QuoteResultGenericQuoteOtherProducts OtherProducts {
        get {
            return this.otherProductsField;
        }
        set {
            this.otherProductsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BGL.CompareTheMarket.Services.DistributorService.DataContracts")]
public partial class QuoteResultGenericQuoteOtherProducts {
    
    private GenericProduct[] featuresField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Feature", IsNullable=false)]
    public GenericProduct[] Features {
        get {
            return this.featuresField;
        }
        set {
            this.featuresField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BGL.CompareTheMarket.Services.DistributorService.DataContracts")]
public partial class QuotesType {
    
    private QuoteResultGenericQuote quoteField;
    
    /// <remarks/>
    public QuoteResultGenericQuote Quote {
        get {
            return this.quoteField;
        }
        set {
            this.quoteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BGL.CompareTheMarket.Services.DistributorService.DataContracts")]
public partial class QuoteResultTypeMessages {
    
    private QuoteResultTypeMessagesGeneralMessages generalMessagesField;
    
    /// <remarks/>
    public QuoteResultTypeMessagesGeneralMessages GeneralMessages {
        get {
            return this.generalMessagesField;
        }
        set {
            this.generalMessagesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://BGL.CompareTheMarket.Services.DistributorService.DataContracts")]
public partial class QuoteResultTypeMessagesGeneralMessages {
    
    private MessageDetailsType messageField;
    
    /// <remarks/>
    public MessageDetailsType Message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
}
