//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://comparethemarket.co.uk/Pet/V1/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://comparethemarket.co.uk/Pet/V1/", IsNullable=false)]
public partial class QuoteRequest {
    
    private QuoteRequestLead leadField;
    
    /// <remarks/>
    public QuoteRequestLead Lead {
        get {
            return this.leadField;
        }
        set {
            this.leadField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://comparethemarket.co.uk/Pet/V1/")]
public partial class QuoteRequestLead {
    
    private RiskMasterType riskMasterField;
    
    /// <remarks/>
    public RiskMasterType RiskMaster {
        get {
            return this.riskMasterField;
        }
        set {
            this.riskMasterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comparethemarket.co.uk/Pet/V1/")]
public partial class RiskMasterType {
    
    private int proposerIDField;
    
    private int addressIDField;
    
    private PersonsDetailsType personsField;
    
    private AddressesType addressesField;
    
    private PetsDetailsType petsField;
    
    private RiskDateTime startDateField;
    
    /// <remarks/>
    public int ProposerID {
        get {
            return this.proposerIDField;
        }
        set {
            this.proposerIDField = value;
        }
    }
    
    /// <remarks/>
    public int AddressID {
        get {
            return this.addressIDField;
        }
        set {
            this.addressIDField = value;
        }
    }
    
    /// <remarks/>
    public PersonsDetailsType Persons {
        get {
            return this.personsField;
        }
        set {
            this.personsField = value;
        }
    }
    
    /// <remarks/>
    public AddressesType Addresses {
        get {
            return this.addressesField;
        }
        set {
            this.addressesField = value;
        }
    }
    
    /// <remarks/>
    public PetsDetailsType Pets {
        get {
            return this.petsField;
        }
        set {
            this.petsField = value;
        }
    }
    
    /// <remarks/>
    public RiskDateTime StartDate {
        get {
            return this.startDateField;
        }
        set {
            this.startDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comparethemarket.co.uk/Pet/V1/")]
public partial class PersonsDetailsType {
    
    private PersonDetailsType personField;
    
    /// <remarks/>
    public PersonDetailsType Person {
        get {
            return this.personField;
        }
        set {
            this.personField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comparethemarket.co.uk/Pet/V1/")]
public partial class PersonDetailsType {
    
    private int idField;
    
    private TitleType titleField;
    
    private RiskString firstNameField;
    
    private RiskString surnameField;
    
    private RiskDate dOBField;
    
    private RiskString emailField;
    
    /// <remarks/>
    public int ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public TitleType Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public RiskString FirstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    public RiskString Surname {
        get {
            return this.surnameField;
        }
        set {
            this.surnameField = value;
        }
    }
    
    /// <remarks/>
    public RiskDate DOB {
        get {
            return this.dOBField;
        }
        set {
            this.dOBField = value;
        }
    }
    
    /// <remarks/>
    public RiskString Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comparethemarket.co.uk/Pet/V1/")]
public partial class TitleType {
    
    private TitleValue valueField;
    
    /// <remarks/>
    public TitleValue Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comparethemarket.co.uk/Pet/V1/")]
public enum TitleValue {
    
    /// <remarks/>
    MR,
    
    /// <remarks/>
    MRS,
    
    /// <remarks/>
    MS,
    
    /// <remarks/>
    MISS,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comparethemarket.co.uk/Pet/V1/")]
public partial class RiskDateTime {
    
    private System.DateTime valueField;
    
    /// <remarks/>
    public System.DateTime Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comparethemarket.co.uk/Pet/V1/")]
public partial class RiskBooleanFixedFalse {
    
    private bool valueField;
    
    public RiskBooleanFixedFalse() {
        this.valueField = false;
    }
    
    /// <remarks/>
    public bool Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comparethemarket.co.uk/Pet/V1/")]
public partial class RiskBooleanFixedTrue {
    
    private bool valueField;
    
    public RiskBooleanFixedTrue() {
        this.valueField = true;
    }
    
    /// <remarks/>
    public bool Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comparethemarket.co.uk/Pet/V1/")]
public partial class RiskDecimal {
    
    private decimal valueField;
    
    /// <remarks/>
    public decimal Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comparethemarket.co.uk/Pet/V1/")]
public partial class RiskBoolean {
    
    private bool valueField;
    
    /// <remarks/>
    public bool Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comparethemarket.co.uk/Pet/V1/")]
public partial class BreedType {
    
    private string valueField;
    
    /// <remarks/>
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comparethemarket.co.uk/Pet/V1/")]
public partial class GenderType {
    
    private GenderValue valueField;
    
    /// <remarks/>
    public GenderValue Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comparethemarket.co.uk/Pet/V1/")]
public enum GenderValue {
    
    /// <remarks/>
    MALE,
    
    /// <remarks/>
    FEMALE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comparethemarket.co.uk/Pet/V1/")]
public partial class PetType {
    
    private PetValue valueField;
    
    /// <remarks/>
    public PetValue Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comparethemarket.co.uk/Pet/V1/")]
public enum PetValue {
    
    /// <remarks/>
    CAT,
    
    /// <remarks/>
    DOG,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comparethemarket.co.uk/Pet/V1/")]
public partial class PetDetailsType {
    
    private int idField;
    
    private PetType typeField;
    
    private RiskString nameField;
    
    private GenderType genderField;
    
    private RiskDate dOBField;
    
    private BreedType breedField;
    
    private RiskBoolean crossbreedField;
    
    private RiskDecimal amountPaidField;
    
    private RiskBoolean chippedField;
    
    private RiskBoolean neuteredField;
    
    private RiskBooleanFixedTrue vaccinatedField;
    
    private RiskBooleanFixedFalse guardOrRacingField;
    
    private RiskBooleanFixedFalse aggressiveField;
    
    private RiskBooleanFixedFalse legalActionField;
    
    /// <remarks/>
    public int ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public PetType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public RiskString Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public GenderType Gender {
        get {
            return this.genderField;
        }
        set {
            this.genderField = value;
        }
    }
    
    /// <remarks/>
    public RiskDate DOB {
        get {
            return this.dOBField;
        }
        set {
            this.dOBField = value;
        }
    }
    
    /// <remarks/>
    public BreedType Breed {
        get {
            return this.breedField;
        }
        set {
            this.breedField = value;
        }
    }
    
    /// <remarks/>
    public RiskBoolean Crossbreed {
        get {
            return this.crossbreedField;
        }
        set {
            this.crossbreedField = value;
        }
    }
    
    /// <remarks/>
    public RiskDecimal AmountPaid {
        get {
            return this.amountPaidField;
        }
        set {
            this.amountPaidField = value;
        }
    }
    
    /// <remarks/>
    public RiskBoolean Chipped {
        get {
            return this.chippedField;
        }
        set {
            this.chippedField = value;
        }
    }
    
    /// <remarks/>
    public RiskBoolean Neutered {
        get {
            return this.neuteredField;
        }
        set {
            this.neuteredField = value;
        }
    }
    
    /// <remarks/>
    public RiskBooleanFixedTrue Vaccinated {
        get {
            return this.vaccinatedField;
        }
        set {
            this.vaccinatedField = value;
        }
    }
    
    /// <remarks/>
    public RiskBooleanFixedFalse GuardOrRacing {
        get {
            return this.guardOrRacingField;
        }
        set {
            this.guardOrRacingField = value;
        }
    }
    
    /// <remarks/>
    public RiskBooleanFixedFalse Aggressive {
        get {
            return this.aggressiveField;
        }
        set {
            this.aggressiveField = value;
        }
    }
    
    /// <remarks/>
    public RiskBooleanFixedFalse LegalAction {
        get {
            return this.legalActionField;
        }
        set {
            this.legalActionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comparethemarket.co.uk/Pet/V1/")]
public partial class RiskString {
    
    private string valueField;
    
    /// <remarks/>
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comparethemarket.co.uk/Pet/V1/")]
public partial class RiskDate {
    
    private System.DateTime valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comparethemarket.co.uk/Pet/V1/")]
public partial class PetsDetailsType {
    
    private PetDetailsType petField;
    
    /// <remarks/>
    public PetDetailsType Pet {
        get {
            return this.petField;
        }
        set {
            this.petField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comparethemarket.co.uk/Pet/V1/")]
public partial class RiskStringNillable {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comparethemarket.co.uk/Pet/V1/")]
public partial class AddressType {
    
    private int idField;
    
    private RiskString addressLine1Field;
    
    private RiskStringNillable addressLine2Field;
    
    private RiskStringNillable addressLine3Field;
    
    private RiskStringNillable addressLine4Field;
    
    private RiskString postCodeField;
    
    /// <remarks/>
    public int ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public RiskString AddressLine1 {
        get {
            return this.addressLine1Field;
        }
        set {
            this.addressLine1Field = value;
        }
    }
    
    /// <remarks/>
    public RiskStringNillable AddressLine2 {
        get {
            return this.addressLine2Field;
        }
        set {
            this.addressLine2Field = value;
        }
    }
    
    /// <remarks/>
    public RiskStringNillable AddressLine3 {
        get {
            return this.addressLine3Field;
        }
        set {
            this.addressLine3Field = value;
        }
    }
    
    /// <remarks/>
    public RiskStringNillable AddressLine4 {
        get {
            return this.addressLine4Field;
        }
        set {
            this.addressLine4Field = value;
        }
    }
    
    /// <remarks/>
    public RiskString PostCode {
        get {
            return this.postCodeField;
        }
        set {
            this.postCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://comparethemarket.co.uk/Pet/V1/")]
public partial class AddressesType {
    
    private AddressType addressField;
    
    /// <remarks/>
    public AddressType Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
}
